/* Procedural combat and location sound effects: no external SFX assets required. */
(function(){
'use strict';
const KEY='badfodder.sfx.v1',VOLUME_KEY='badfodder.sfx.volume.v1';let enabled=true,volume=.58;
try{const storage=typeof BadFodderStorage!=='undefined'?BadFodderStorage.local:localStorage,saved=storage.getItem(KEY),savedVolume=storage.getItem(VOLUME_KEY);if(saved!==null)enabled=saved!=='0';if(savedVolume!==null&&Number.isFinite(Number(savedVolume)))volume=Math.max(0,Math.min(1,Number(savedVolume)))}catch(_){}
let ctx=null,master=null,compressor=null,noiseBuffer=null,lastSquadShot=0,lastEnemyShot=0,lastScuffle=0,lastCrowd=0,lastMounted=0,lastBarricade=0,lastImpact=0,lastEnvironment=0;
const button=document.getElementById('menuSfx');let volumeInput=null,volumeValue=null;
const masterLevel=()=>.55*volume;
function ensureAudio(){if(ctx){try{window.BadFodderProceduralSfx?.init?.(ctx)}catch(_){}return ctx}const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;ctx=new AudioContext();master=ctx.createGain();master.gain.value=enabled?masterLevel():0;compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=14;compressor.ratio.value=8;compressor.attack.value=.003;compressor.release.value=.18;master.connect(compressor);compressor.connect(ctx.destination);noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const data=noiseBuffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){const white=Math.random()*2-1;last=last*.82+white*.18;data[i]=white*.72+last*.28}try{window.BadFodderProceduralSfx?.init?.(ctx)}catch(_){}return ctx}
async function unlock(){const audio=ensureAudio();if(!audio)return;if(audio.state==='suspended')try{await audio.resume()}catch(_){}}
function ready(){if(!enabled||volume<=0)return null;const audio=ensureAudio();return audio&&audio.state==='running'?audio:null}
function gainEnvelope(audio,level,attack,hold,release){const gain=audio.createGain(),now=audio.currentTime;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,level),now+attack);gain.gain.setValueAtTime(Math.max(.0001,level),now+attack+hold);gain.gain.exponentialRampToValueAtTime(.0001,now+attack+hold+release);gain.connect(master);return{gain,now,end:now+attack+hold+release}}
function noiseBurst({volume=.12,duration=.08,filter='bandpass',frequency=1000,q=.8}={}){const audio=ready();if(!audio||!noiseBuffer)return;const env=gainEnvelope(audio,volume,.002,Math.max(.001,duration*.25),Math.max(.01,duration*.75)),src=audio.createBufferSource(),biquad=audio.createBiquadFilter();src.buffer=noiseBuffer;biquad.type=filter;biquad.frequency.setValueAtTime(frequency,env.now);biquad.Q.value=q;src.connect(biquad);biquad.connect(env.gain);const offset=Math.random()*Math.max(0,noiseBuffer.duration-duration-.02);src.start(env.now,offset,duration+.04);src.stop(env.end+.03)}
function tone({type='square',from=220,to=90,volume=.08,duration=.07,delay=0}={}){const audio=ready();if(!audio)return;const gain=audio.createGain(),start=audio.currentTime+Math.max(0,delay),end=start+duration;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,volume),start+.002);gain.gain.exponentialRampToValueAtTime(.0001,end);gain.connect(master);const osc=audio.createOscillator();osc.type=type;osc.frequency.setValueAtTime(Math.max(20,from),start);osc.frequency.exponentialRampToValueAtTime(Math.max(20,to),end);osc.connect(gain);osc.start(start);osc.stop(end+.02)}
function shoot(owner='squad'){if(!ready())return;const now=performance.now();if(owner==='squad'){if(now-lastSquadShot<48)return;lastSquadShot=now}else{if(now-lastEnemyShot<72)return;lastEnemyShot=now}const player=owner==='squad',variance=.94+Math.random()*.12;noiseBurst({volume:player?.16:.095,duration:player?.065:.055,filter:'bandpass',frequency:(player?1450:1120)*variance,q:.55});tone({type:'square',from:(player?235:195)*variance,to:(player?78:68)*variance,volume:player?.085:.055,duration:.055})}
function impact(kind='target'){if(!ready())return;const now=performance.now();if(now-lastImpact<36)return;lastImpact=now;const body=kind==='body',variance=.9+Math.random()*.2;noiseBurst({volume:body?.095:.07,duration:body?.075:.045,filter:body?'lowpass':'bandpass',frequency:(body?620:1850)*variance,q:body?.45:1.1});tone({type:'triangle',from:(body?150:520)*variance,to:(body?72:180)*variance,volume:body?.035:.024,duration:body?.075:.04})}
function grenadeThrow(){if(!ready())return;noiseBurst({volume:.085,duration:.19,filter:'bandpass',frequency:720,q:.45});tone({type:'triangle',from:620,to:145,volume:.045,duration:.2})}
function explosion(){if(!ready())return;noiseBurst({volume:.42,duration:.58,filter:'lowpass',frequency:760,q:.25});noiseBurst({volume:.16,duration:.22,filter:'bandpass',frequency:1700,q:.35});tone({type:'sine',from:105,to:34,volume:.3,duration:.46})}
function death(team='enemy'){if(!ready())return;const squadDeath=team==='squad',variance=.9+Math.random()*.2;noiseBurst({volume:squadDeath?.105:.075,duration:.22,filter:'bandpass',frequency:390*variance,q:1.25});tone({type:'sawtooth',from:(squadDeath?175:195)*variance,to:(squadDeath?72:88)*variance,volume:squadDeath?.075:.05,duration:.24})}
function scuffle(kind='shove'){if(!ready())return;const now=performance.now();if(now-lastScuffle<105)return;lastScuffle=now;if(kind==='brick'){noiseBurst({volume:.11,duration:.055,filter:'bandpass',frequency:1350,q:.7});tone({type:'triangle',from:310,to:135,volume:.035,duration:.05})}else if(kind==='stick'){noiseBurst({volume:.085,duration:.045,filter:'highpass',frequency:1700,q:.6});tone({type:'square',from:250,to:115,volume:.03,duration:.045})}else{noiseBurst({volume:.12,duration:.075,filter:'lowpass',frequency:720,q:.4});tone({type:'sine',from:115,to:62,volume:.055,duration:.075})}}
function barricade(kind='build'){if(!ready())return;const now=performance.now();if(now-lastBarricade<180)return;lastBarricade=now;const collapse=kind==='collapse';noiseBurst({volume:collapse?.14:.075,duration:collapse?.32:.09,filter:'lowpass',frequency:collapse?650:1500,q:.5});tone({type:'triangle',from:collapse?155:370,to:collapse?48:120,volume:.04,duration:collapse?.22:.08})}
function crowdSurge(){if(!ready())return;const now=performance.now();if(now-lastCrowd<900)return;lastCrowd=now;noiseBurst({volume:.075,duration:.48,filter:'bandpass',frequency:520,q:.32});noiseBurst({volume:.045,duration:.36,filter:'bandpass',frequency:920,q:.45});tone({type:'triangle',from:150,to:105,volume:.022,duration:.34})}
function mountedCharge(){if(!ready())return;const now=performance.now();if(now-lastMounted<1800)return;lastMounted=now;noiseBurst({volume:.12,duration:.42,filter:'lowpass',frequency:430,q:.25});[0,.105,.245,.35].forEach((delay,i)=>tone({type:'sine',from:92+(i%2)*18,to:46,volume:.075,duration:.075,delay}))}
function environment(location,reason='ambient'){if(!ready())return;const now=performance.now();if(reason!=='enter'&&now-lastEnvironment<6500)return;lastEnvironment=now;if(location==='bad-belzig'){tone({type:'sine',from:520,to:505,volume:.012,duration:.42});tone({type:'sine',from:780,to:760,volume:.008,duration:.34,delay:.18})}else if(location==='wigan'){noiseBurst({volume:.018,duration:.16,filter:'bandpass',frequency:1450,q:1.8});tone({type:'triangle',from:180,to:125,volume:.012,duration:.12,delay:.05})}else if(location==='cable-street'){noiseBurst({volume:.018,duration:.35,filter:'bandpass',frequency:610,q:.4})}else if(location==='barcelona'){noiseBurst({volume:.012,duration:.42,filter:'highpass',frequency:2100,q:.35});tone({type:'sine',from:330,to:300,volume:.008,duration:.3})}}
function installVolumeControl(){if(!button||volumeInput||typeof document.createElement!=='function')return;const label=document.createElement('label');label.className='menu-setting menu-volume';label.setAttribute('for','menuSfxVolume');const title=document.createElement('span');title.textContent='SFX VOLUME';const control=document.createElement('span');control.className='menu-range-control';volumeInput=document.createElement('input');volumeInput.id='menuSfxVolume';volumeInput.type='range';volumeInput.min='0';volumeInput.max='100';volumeInput.step='1';volumeValue=document.createElement('output');volumeValue.id='menuSfxVolumeValue';volumeValue.setAttribute('for','menuSfxVolume');control.append(volumeInput,volumeValue);label.append(title,control);button.insertAdjacentElement?.('afterend',label);volumeInput.addEventListener('input',event=>setVolume(Number(event.target.value)/100));}
function render(){if(button){button.textContent=enabled?'SFX: ON':'SFX: OFF';button.setAttribute('aria-pressed',String(enabled))}if(volumeInput)volumeInput.value=String(Math.round(volume*100));if(volumeValue)volumeValue.textContent=Math.round(volume*100)+'%'}
function setVolume(value){const next=Number(value);if(!Number.isFinite(next))return;volume=Math.max(0,Math.min(1,next));try{(typeof BadFodderStorage!=='undefined'?BadFodderStorage.local:localStorage).setItem(VOLUME_KEY,String(volume))}catch(_){}if(master)master.gain.value=enabled?masterLevel():0;render()}
function setEnabled(on){enabled=!!on;try{(typeof BadFodderStorage!=='undefined'?BadFodderStorage.local:localStorage).setItem(KEY,enabled?'1':'0')}catch(_){}if(master)master.gain.value=enabled?masterLevel():0;if(enabled)unlock();window.BadFodderAmbience?.sync();render()}
function toggle(){setEnabled(!enabled)}function arm(event){if(event&&event.target===button)return;unlock()}
addEventListener('pointerdown',arm,{passive:true});addEventListener('touchstart',arm,{passive:true});addEventListener('keydown',arm);if(button)button.addEventListener('click',toggle);installVolumeControl();
window.BadFodderSfx={unlock,shoot,impact,grenadeThrow,explosion,death,scuffle,barricade,crowdSurge,mountedCharge,environment,toggle,setEnabled,setVolume,get audioContext(){return ctx},get enabled(){return enabled},get volume(){return volume}};
render();
})();
