'use strict';
const assert=require('node:assert/strict'),C=require('../civilian-runtime'),R=require('../mission-objectives'),P=require('../multiplayer-protocol');
const residents=Array.from({length:6},(_,i)=>({x:200+i*4,y:0,homeX:200,y:0,homeY:0,phase:i,speed:40}));
const squad=[{x:200,y:0,alive:true}],enemies=[],noise=[],events=[];let paths=0;
const runtime=C.create({getCivilians:()=>residents,getSquad:()=>squad,getEnemies:()=>enemies,getNoise:()=>noise,zones:[{x:0,y:0,r:35}],path:()=>paths++,follow:()=>true,onEvent:(event)=>events.push(event)});
assert.equal(runtime.hint(squad[0]),'GATHER');assert(runtime.interact(squad[0]));assert.equal(runtime.counts().following,6);
assert.equal(runtime.hint(squad[0]),'HIDE');runtime.interact(squad[0]);assert(residents.every(c=>c.civilianState==='HIDING'));runtime.interact(squad[0]);
squad[0].x=0;runtime.update(.1);assert(paths<=2,'Path work must have a per-step budget');
residents[0].x=0;enemies.push({x:10,y:0,alive:true});runtime.update(.1);assert.notEqual(residents[0].civilianState,'EVACUATED','Contested exit is unsafe');
enemies.length=0;runtime.update(.1);assert.equal(runtime.counts().evacuated,1);runtime.damage(residents[0],99);assert.equal(runtime.counts().evacuated,1,'Evacuated residents are safe');
squad[0].x=200;runtime.damage(residents[1],4);assert.equal(residents[1].civilianState,'DOWN');runtime.update(1);assert.equal(runtime.hint(squad[0]),'HELP');assert(runtime.interact(squad[0]));assert.equal(residents[1].hp,1);assert.equal(residents[1].civilianState,'WOUNDED');
runtime.damage(residents[2],4);runtime.update(19);assert.equal(runtime.counts().lost,1);assert(events.includes('lost'));
squad[0].alive=false;runtime.update(.1);assert(residents.filter(c=>c.alive&&c.civilianState!=='EVACUATED').every(c=>c.leaderIndex===null));assert(events.includes('separated'));
const clone=residents.map(c=>({...c})),copy=C.create({getCivilians:()=>clone,getSquad:()=>squad});copy.receive(runtime.snapshot());assert.deepEqual(copy.snapshot(),runtime.snapshot());
const objective=R.create({objectives:[{id:'exit',type:'ESCAPE',marker:{x:0,y:0,r:10}},{id:'residents',type:'EVACUATE',optional:true,priority:-10,status:'ACTIVE'}]});
objective.signal('residents');objective.update(.1,{living:[]});assert.equal(objective.manager.get('residents').status,'COMPLETED');assert(!objective.manager.missionState().failed);
const actor={x:0,y:0,alive:true,hp:8,maxHp:8,dir:0,state:'idle'};
const packet=P.snapshot({squad:Array(4).fill(actor),enemies:[],civilians:residents,pickups:[],bullets:[],thrown:[],effects:[],missionStage:0,phaseHoldTime:0,squadGrenades:5,finished:false,win:false,checkpoint:null,stats:Array.from({length:4},(_,index)=>({index,name:'Local',kills:0,alive:true})),civilianState:runtime.snapshot()},1);
assert.deepEqual(P.readSnapshot(packet).civilianState,runtime.snapshot());assert(!P.readSnapshot({...packet,civilianState:[['FOLLOWING',99,null]]}));
// New mission groups share initialization and stop before a live hostile on their route.
const group=[],leaders=[{x:100,y:0,alive:true}],threats=[{x:65,y:0,alive:true}],steps=[];
const navigation=C.create({getCivilians:()=>group,getSquad:()=>leaders,getEnemies:()=>threats,path:c=>{c.path=[{x:60,y:0}];c.pathIndex=0},follow:c=>{steps.push(c);return true}});
const follower=navigation.add({x:0,y:0,homeX:0,homeY:0,speed:35,civilianState:'HIDING'});assert.equal(follower.civilianState,'HIDING');follower.leaderIndex=0;navigation.update(.1);assert.equal(steps.length,0);assert.equal(follower.civilianState,'HIDING');threats[0].missionDormant=true;navigation.update(.1);assert.equal(steps.length,1,'Dormant troops cannot block civilian extraction');
console.log('PASS: gathering/hiding, bounded navigation, unsafe exits, evacuation, rescue, loss, separation, optional outcomes and co-op civilian states.');
