'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const scope={window:{}};vm.createContext(scope);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../scenery-cache.js'),'utf8'),scope);
let paints=0;const draws=[];
const cache=new scope.window.BadFodderScenery({width:1500,height:1500,size:512,limit:4,paint:(x,y,w,h)=>({x,y,w,h,id:++paints})});
const ctx={drawImage:(tile,x,y)=>draws.push({tile,x,y})};
cache.draw(ctx,0,0,500,500);assert.equal(paints,1);assert.equal(draws[0].tile.w,512);
cache.draw(ctx,10,10,400,400);assert.equal(paints,1,'Stable view reuses native-resolution tile');
cache.draw(ctx,1024,1024,400,400);assert.equal(draws.at(-1).tile.w,476);assert.equal(draws.at(-1).tile.h,476);
cache.draw(ctx,0,0,1500,1500);assert.equal(cache.tiles.size,9,'Visible tiles are retained even beyond nominal limit');
const after=paints;cache.draw(ctx,0,0,1500,1500);assert.equal(paints,after,'Zooming out must not thrash the cache');
cache.draw(ctx,0,0,100,100);assert.equal(cache.tiles.size,4,'Off-screen tiles are evicted');
const empty=draws.length;cache.draw(ctx,1600,1600,20,20);assert.equal(draws.length,empty);
const padded=new scope.window.BadFodderScenery({width:1500,height:1500,gutter:2,paint:(x,y,w,h)=>({x,y,w,h})});
padded.draw(ctx,512.5,512.5,10,10);
const edge=draws.at(-1);assert.equal(edge.tile.x,510);assert.equal(edge.tile.y,510);
assert.equal(edge.tile.w,516);assert.equal(edge.tile.h,516);assert.equal(edge.x,510);assert.equal(edge.y,510);
padded.draw(ctx,1024,1024,10,10);assert.equal(draws.at(-1).tile.w,480,'World edge tiles retain their seam gutter');
console.log('PASS: native tile sizes, cache reuse, world edges, zoomed-out retention, eviction and seam gutters.');
