'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');
const Objectives=require('../mission-objectives.js');
const root=path.join(__dirname,'..');
const map=new Function(fs.readFileSync(path.join(root,'wigan-map.js'),'utf8')+';return WIGAN_MAP;')();
const scope={window:{BadFodderHistoricalMissions:require('../historical-missions')},localStorage:{getItem:()=>null,setItem(){}}};
vm.runInNewContext(fs.readFileSync(path.join(root,'campaign.js'),'utf8'),scope);
const mission=scope.window.BadFodderCampaign.missions.find(m=>m.id==='wigan');
const zones=Object.fromEntries(Object.entries(map.zones).map(([key,z])=>[key,{x:z.x*2,y:z.y*2,r:z.r*2}]));
const at=key=>({x:zones[key].x,y:zones[key].y,alive:true});
const context=key=>({living:[at(key)],enemies:[],zones});

const story=Objectives.create(mission);
assert.equal(story.manager.current().title,'Rally at Tudor House');
story.update(2.5,context('tudor'));
assert.equal(story.facts.get('tudor_group'),'CONNECTED');
assert.equal(story.facts.get('bus_group'),'CONTACTED');
assert.equal(story.manager.current().title,'Reconnect the Town Centre');
let result=story.evaluate(story.manager.current(),context('grandArcade'));
assert.equal(result.ready,false,'Grand Arcade must not skip the Market Place connection');
assert.match(result.status,/Market Place/);
story.update(0,context('market'));
assert.equal(story.facts.get('market_group'),'CONNECTED');
assert.equal(story.facts.get('bus_group'),'CONNECTED');
result=story.evaluate(story.manager.current(),context('grandArcade'));
assert.equal(result.ready,true,'Grand Arcade should open after the town-centre route is connected');
story.update(2.8,context('grandArcade'));
assert.equal(story.facts.get('grand_arcade_status'),'HELD');
assert.equal(story.facts.get('network_status'),'DISRUPTED');
assert.equal(story.facts.get('railway_group'),'CONTACTED');
result=story.evaluate(story.manager.current(),context('wallgate'));
assert.equal(result.ready,false,'Wallgate should wait for the cut network to be restored');
story.update(0,context('market'));
assert.equal(story.facts.get('network_status'),'RESTORED');
result=story.evaluate(story.manager.current(),context('wallgate'));
assert.equal(result.ready,true,'Wallgate should open once the network is restored');
story.update(3,context('wallgate'));
assert.equal(story.facts.get('railway_group'),'CONNECTED');
assert.equal(story.facts.get('network_status'),'COORDINATED');
assert(story.manager.missionState().complete,'Wigan network flow should finish the mission');

const alternate=Objectives.create(mission);
alternate.update(2.5,context('tudor'));
alternate.update(0,context('market'));
alternate.update(0,context('kingStreet'));
assert.equal(alternate.facts.get('king_group'),'CONNECTED');
alternate.update(2.8,context('grandArcade'));
assert.equal(alternate.facts.get('network_status'),'RESTORED','King Street should provide an alternate route when the centre is cut');
assert.match(alternate.evaluate(alternate.manager.current(),context('wallgate')).status,/King Street support/);

console.log('PASS: Wigan now progresses from Tudor rally to Market Place connection, Grand Arcade disruption, optional King Street support and a coordinated Wallgate finale.');
