'use strict';
const {test,expect}=require('@playwright/test');
async function prepare(page){await page.goto('/?seed=visual-42');await page.waitForFunction(()=>!!window.__visual);await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important}'});const skip=page.locator('[data-presentation-skip]');if(await skip.isVisible())await skip.click();}
async function choose(page,button){await page.locator('#menuMissionSelect').click();await page.locator(button).click();}
test('main menu and briefing',async({page})=>{await prepare(page);await expect(page.locator('#menuInstall')).toBeVisible();await expect(page.locator('#menuInstall')).toHaveText('INSTALL GAME');await expect(page).toHaveScreenshot('main-menu.png',{maxDiffPixelRatio:.025});await choose(page,'#menuMissionBad');await page.evaluate(()=>BadFodderArt.preloadMissionArt('belzig'));await expect(page).toHaveScreenshot('briefing.png');});
for(const [key,button] of [['bad-belzig','#menuMissionBad'],['wigan','#menuMissionWigan'],['cable-street','#menuHistoricalCable']])test(key+' scenery and actors',async({page})=>{
 await prepare(page);await choose(page,button);await page.locator('#briefingBegin').click();await page.waitForFunction(()=>window.__visual?.state().started&&!window.__visual.state().menuOpen&&window.__visual.state().actors===4);await page.evaluate(()=>window.__visual.freeze());expect(await page.evaluate(()=>window.__visual.state().faults)).toBe(0);await expect(page.locator('.viewport')).toHaveScreenshot(key+'.png');
});
test('mobile HUD',async({browser})=>{const context=await browser.newContext({viewport:{width:915,height:412},hasTouch:true,isMobile:true,reducedMotion:'reduce',locale:'en-GB',colorScheme:'dark'});const page=await context.newPage();await prepare(page);await choose(page,'#menuMissionBad');await page.locator('#briefingBegin').click();await page.waitForFunction(()=>window.__visual?.state().started&&!window.__visual.state().menuOpen&&window.__visual.state().actors===4);await page.evaluate(()=>window.__visual.freeze());await expect(page.locator('.viewport')).toHaveScreenshot('mobile-hud.png');await context.close();});
