'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
const Registry=require(path.join(root,'mission-registry.js'));
const Rng=require(path.join(root,'game-rng.js'));
const Objectives=require(path.join(root,'mission-objectives.js'));
const Navigation=require(path.join(root,'navigation.js'));
const EnemyBehaviour=require(path.join(root,'enemy-behaviour.js'));
const Tactics=require(path.join(root,'combat-tactics.js'));
const Adaptive=require(path.join(root,'adaptive-director.js'));
const Health=require(path.join(root,'character-health.js'));
const Civilians=require(path.join(root,'civilian-runtime.js'));
const BarcelonaRuntime=require(path.join(root,'barcelona-runtime.js'));
const Cable=require(path.join(root,'cable-street-runtime.js'));
const CableInteractions=require(path.join(root,'cable-street-interactions.js'));
const CableDirector=require(path.join(root,'cable-street-director.js'));
const CableCrowd=require(path.join(root,'cable-street-crowd.js'));
const CableVerify=require(path.join(root,'tools/cable-street/verify-release.cjs'));
const Historical=require(path.join(root,'historical-missions.js'));

const FIXED_DT=1/60,DEFAULT_MAX_SECONDS=12*60;
const DIFFICULTY=Object.freeze({story:{playerHit:.72,enemyHit:.10,enemyDamage:.75,speed:1.08},standard:{playerHit:.58,enemyHit:.15,enemyDamage:1,speed:1},resistance:{playerHit:.48,enemyHit:.20,enemyDamage:1.2,speed:.96}});
const mapCache=new Map();let campaignCache=null,cableSource=null;
function loadCampaign(){if(campaignCache)return campaignCache;const storage={getItem:()=>null,setItem(){}},scope={window:{BadFodderHistoricalMissions:Historical},localStorage:storage};vm.runInNewContext(fs.readFileSync(path.join(root,'campaign.js'),'utf8'),scope);return campaignCache=scope.window.BadFodderCampaign}
function loadScriptMap(files,name){const key=files.join('|');if(mapCache.has(key))return mapCache.get(key);const source=files.map(file=>fs.readFileSync(path.join(root,file),'utf8')).join('\n'),map=new Function(source+'\n;return '+name+';')();mapCache.set(key,map);return map}
function missionFor(ref){const definition=Registry.get(ref);if(!definition)throw new Error('Unknown mission: '+ref);const campaign=loadCampaign(),mission=campaign.missions.find(m=>m.id===definition.id||m.legacyId===definition.id||m.map===definition.map.key);if(!mission)throw new Error('No campaign mission for '+definition.id);return{definition,mission}}
function mapFor(definition){switch(definition.map.key){case'bad-belzig':return loadScriptMap(['town-map.js','bad-belzig-data.js'],'TOWN_MAP');case'wigan':return loadScriptMap(['wigan-map.js'],'WIGAN_MAP');case'barcelona':return require(path.join(root,'barcelona-map.js'));case'cable-street':if(!cableSource){const checked=CableVerify.verifyDirectory(path.join(root,'authoring/cable-street'));if(!checked.report.ready)throw new Error('Cable Street authoring is not release-ready: '+checked.report.problems.join('; '));cableSource=checked.map}return cableSource;default:throw new Error('Unsupported mission map: '+definition.map.key)}}
function scaledBuildings(map,scale){return(map.buildings||[]).map(b=>{const points=b.points.map(p=>p.map(v=>v*scale)),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return{...b,points,minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}})}
function createNavigation(map,scale=2){let navigation;const moveEntity=(u,dx,dy,r=6)=>{if(!navigation.obstacleAt(u.x+dx,u.y,r))u.x+=dx;if(!navigation.obstacleAt(u.x,u.y+dy,r))u.y+=dy};navigation=Navigation.create({worldWidth:map.width*scale,worldHeight:map.height*scale,buildings:scaledBuildings(map,scale),mapKey:map.key,moveEntity,updateFacing(u,dx,dy){if(dx||dy)u.dir=Math.atan2(dy,dx)}});return navigation}
function zonesFor(map,scale=2){if(map.zones)return Object.fromEntries(Object.entries(map.zones).map(([k,z])=>[k,{...z,x:z.x*scale,y:z.y*scale,r:(z.r||50)*scale}]));return{post:{x:map.pois.postcolumn.x*scale,y:map.pois.postcolumn.y*scale,r:46*scale},castle:{x:map.pois.castle.x*scale,y:map.pois.castle.y*scale,r:82*scale},market:{x:map.pois.market.x*scale,y:map.pois.market.y*scale,r:86*scale}}}
const difficulty=name=>DIFFICULTY[name]||DIFFICULTY.standard,aliveSquad=squad=>squad.filter(s=>s.alive!==false&&!s.downed),hostiles=enemies=>enemies.filter(e=>e.alive!==false&&!e.surrendered&&!e.missionDormant&&!e.missionWithdrawn),dist=(a,b)=>Math.hypot((a.x||0)-(b.x||0),(a.y||0)-(b.y||0));
function nearest(from,list){let best=null,bestD=Infinity;for(const item of list){const d=dist(from,item);if(d<bestD){best=item;bestD=d}}return best}
function percentile(values,p){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),i=(sorted.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?sorted[lo]:sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo)}
function objectiveTracker(){const starts=new Map(),completed=new Map(),seen=new Set();let current=null;return{update(time,rows){const active=rows.find(o=>o.status==='ACTIVE')||null;if(active&&active.id!==current){current=active.id;if(!starts.has(active.id))starts.set(active.id,time);seen.add(active.id)}for(const o of rows)if(o.status==='COMPLETED'&&!completed.has(o.id)){completed.set(o.id,time);seen.add(o.id)}},result:()=>[...seen].map(id=>({id,startedAt:starts.get(id)??0,completedAt:completed.get(id)??null,duration:completed.has(id)?completed.get(id)-(starts.get(id)??0):null}))}}
function directorRecorder(director){let last=0;const actions=[];return{tick(time){const count=director?.state?.decisions||0;if(count<=last)return;const history=director.state.history||[];while(last<count){actions.push({time,action:history[history.length-(count-last)]||history.at(-1)||'UNKNOWN'});last++}},actions}}
function baseResult({mission,seed,difficultyName,seconds,won,failureReason,objective,objectives,squad,enemies,ammoStart,ammoEnd,grenadesStart,grenadesEnd,directorActions,peakEnemies,combatSeconds,idleSeconds,stalls,civiliansFound=0,civiliansRescued=0,civiliansLost=0,shotsFired=0,shotsHit=0,skillFactor=1}){const survivors=squad.filter(s=>s.alive!==false).length,downed=squad.filter(s=>s.downed).length,wounded=squad.filter(s=>s.alive!==false&&!s.downed&&Health.stateFor(s)!=='FIT').length,damageTaken=squad.reduce((n,s)=>n+Math.max(0,(Number(s.maxHp)||0)-Math.max(0,Number(s.hp)||0)),0);return{missionId:mission.id,map:mission.map,seed:String(seed),difficulty:difficultyName,victory:!!won,failure:!won,durationSeconds:+seconds.toFixed(3),objectiveReached:objective||null,objectives,squad:{start:squad.length,survivors,casualties:squad.length-survivors,wounded,downed,damageTaken:+damageTaken.toFixed(3)},civilians:{found:civiliansFound,rescued:civiliansRescued,lost:civiliansLost},enemiesDefeated:enemies.filter(e=>e.alive===false).length,ammo:{start:ammoStart,end:ammoEnd,starved:ammoEnd===0&&!won},grenades:{start:grenadesStart,end:grenadesEnd,used:Math.max(0,grenadesStart-grenadesEnd)},director:{decisions:directorActions.length,actions:directorActions},peakActiveEnemies:peakEnemies,timeInCombatSeconds:+combatSeconds.toFixed(3),idleSeconds:+idleSeconds.toFixed(3),idleRatio:seconds?+(idleSeconds/seconds).toFixed(4):0,stalls,retries:0,timeouts:failureReason==='timeout'?1:0,failureReason:won?null:failureReason||'mission-failed',shotsFired,shotsHit,accuracy:shotsFired?+(shotsHit/shotsFired).toFixed(4):null,skillFactor:+skillFactor.toFixed(6)}}
function createStandard({mission,map,seed,difficultyName,maxSeconds}){
 const scale=2,rng=Rng.create(seed),rules=difficulty(difficultyName),skillFactor=.9+rng.random()*.2,zones=zonesFor(map,scale),navigation=createNavigation(map,scale),objectives=Objectives.create(mission),groups=map.defenderGroups||{};
 const groupFor=(x,y,i)=>Object.entries(groups).find(([,ids])=>ids.includes(i))?.[0]||mission.phases.reduce((best,p)=>{const z=zones[p.zone],d=z?Math.hypot(x*scale-z.x,y*scale-z.y):Infinity;return d<best.d?{id:p.defenderGroup,d}:best},{id:null,d:Infinity}).id;
 const squad=(map.spawns?.squad||[]).slice(0,mission.squadSize||4).map(([x,y],i)=>({name:'S'+(i+1),x:x*scale,y:y*scale,alive:true,hp:8,maxHp:8,ammo:60,weapon:'rifle',dir:0,shotCooldown:0})),enemies=(map.spawns?.enemies||[]).map(([x,y],i)=>({x:x*scale,y:y*scale,homeX:x*scale,homeY:y*scale,alive:true,hp:3,maxHp:3,dir:0,objectiveGroup:groupFor(x,y,i),groupId:groupFor(x,y,i)||i,shotCooldown:.2+rng.random()*.7}));
 const rawDamage=(u,amount)=>{if(!u.alive)return;u.hp-=amount;if(u.hp<=0){u.alive=false;u.state='dead'}};Health.bindRuntime({getSquad:()=>squad,getSelected:()=>aliveSquad(squad).slice(0,1),damage:rawDamage});
 const tactics=Tactics.create({getSquad:()=>squad,getEnemies:()=>enemies,obstacleAt:navigation.obstacleAt,canSee:(a,b)=>!navigation.lineBlocked(a.x,a.y,b.x,b.y)}),behaviour=EnemyBehaviour.create({getEnemies:()=>enemies,getSquad:()=>squad}),roads=(map.roads||[]).map(r=>({...r,points:r.points.map(p=>p.map(v=>v*scale))}));let simTime=0;
 const commander=Adaptive.createCommander({getEnemies:()=>enemies,getSquad:()=>squad,getZones:()=>zones,getPhase:()=>{const o=objectives.manager.current();return o?{...o,index:o.phase??0}:null},roads,scale,navigation,blocked:navigation.obstacleAt,queuePath:(e,x,y)=>navigation.assignPath(e,x,y)}),adaptive=Adaptive.create({mission:mission.id,adapter:commander,random:rng.random,debug:true}),director=directorRecorder(adaptive),tracker=objectiveTracker(),checkpointSpawned=new Set();
 let grenades=4,peakEnemies=hostiles(enemies).length,combat=0,idle=0,stalls=0,lastMeaningful=0,lastDecision=-1,shotsFired=0,shotsHit=0,finished=false,won=false,failureReason=null;const ammoStart=squad.reduce((n,s)=>n+s.ammo,0),grenadesStart=grenades;
 function spawnCheckpoint(objective){if(!objective?.checkpoint||checkpointSpawned.has(objective.id))return false;const defenders=hostiles(enemies).filter(e=>e.objectiveGroup===objective.defenderGroup),z=zones[objective.zone];if(defenders.length||!z||!aliveSquad(squad).some(s=>dist(s,z)<=z.r))return false;checkpointSpawned.add(objective.id);const count=objective.checkpoint.count||0;for(let i=0;i<count;i++){const angle=(Math.PI*2*i/Math.max(1,count))+.2,rad=z.r+120+20*(i%2);let x=z.x+Math.cos(angle)*rad,y=z.y+Math.sin(angle)*rad;if(navigation.obstacleAt(x,y,10)){x=z.x+Math.cos(angle+1)*rad;y=z.y+Math.sin(angle+1)*rad}enemies.push({x,y,homeX:x,homeY:y,alive:true,hp:3,maxHp:3,dir:0,objectiveGroup:objective.defenderGroup,groupId:'checkpoint-'+objective.id,shotCooldown:.2+rng.random()*.5})}return count>0}
 function moveActor(actor,target,dt){if(!target||!actor.alive||actor.downed)return false;if(!actor.path||actor.navTargetId!==target._simId){navigation.assignPath(actor,target.x,target.y);actor.navTargetId=target._simId||((target._simId='t'+Math.round(target.x)+'-'+Math.round(target.y)))}const x=actor.x,y=actor.y;navigation.followPath(actor,120*rules.speed*Health.movementScale(actor)*Tactics.movementScale(actor),dt);return Math.hypot(actor.x-x,actor.y-y)>.01}
 function damageEnemy(e,amount,by){if(!e.alive)return false;e.hp-=amount;e.lastHitBy=by;e.lastHitSide='squad';if(e.hp<=0){e.hp=0;e.alive=false;e.state='dead'}return true}
 function combatStep(dt,current){let active=false;const live=aliveSquad(squad),phaseEnemies=hostiles(enemies).filter(e=>!current?.defenderGroup||e.objectiveGroup===current.defenderGroup);for(let i=0;i<squad.length;i++){const s=squad[i];s.shotCooldown=Math.max(0,(s.shotCooldown||0)-dt);if(!s.alive||s.downed||s.ammo<=0)continue;const target=nearest(s,phaseEnemies.filter(e=>dist(s,e)<=300&&!navigation.lineBlocked(s.x,s.y,e.x,e.y)));if(!target||s.shotCooldown>0)continue;active=true;s.shotCooldown=.32+rng.random()*.2;s.ammo--;shotsFired++;const chance=Math.max(.12,Math.min(.9,rules.playerHit*skillFactor/Tactics.spreadScale(s)));if(rng.random()<chance){shotsHit++;damageEnemy(target,1,i)}else tactics.nearShot('squad',s.x,s.y,target.x,target.y)}const currentHostiles=hostiles(enemies).filter(e=>!current?.defenderGroup||e.objectiveGroup===current.defenderGroup),clustered=currentHostiles.filter(e=>live.some(s=>dist(s,e)<110));if(grenades>0&&clustered.length>=3&&rng.random()<dt*.5){grenades--;active=true;for(const e of clustered.slice(0,4))damageEnemy(e,2,0)}for(const e of currentHostiles){e.shotCooldown=Math.max(0,(e.shotCooldown||0)-dt);const target=nearest(e,live.filter(s=>dist(e,s)<=300&&!navigation.lineBlocked(e.x,e.y,s.x,s.y)));if(!target||e.shotCooldown>0)continue;active=true;const mod=EnemyBehaviour.modifiers(e);e.shotCooldown=(.55+rng.random()*.5)/(mod.burst||1);if(rng.random()<rules.enemyHit*(mod.accuracy||1))Health.handleDamage(target,rules.enemyDamage,target.x,target.y,e);else tactics.nearShot('enemy',e.x,e.y,target.x,target.y)}return active}
 function step(dt=FIXED_DT){if(finished)return;simTime+=dt;tracker.update(simTime,objectives.manager.all());const current=objectives.manager.current(),z=current?.zone?zones[current.zone]:null;if(spawnCheckpoint(current))lastMeaningful=simTime;if(simTime-lastDecision>=.5){lastDecision=simTime;const defenders=hostiles(enemies).filter(e=>!current?.defenderGroup||e.objectiveGroup===current.defenderGroup);for(const e of defenders){const s=nearest(e,aliveSquad(squad));if(s&&dist(e,s)<360){e.lastSeen={x:s.x,y:s.y};e.observedAt=simTime}}}let moved=false;const downed=squad.find(s=>s.alive&&s.downed&&!s.stabilised),helper=aliveSquad(squad)[0];if(downed&&helper){moved=moveActor(helper,downed,dt)||moved;if(dist(helper,downed)<=Health.AID_RANGE){Health.stabilise(downed,helper);lastMeaningful=simTime}}const defenders=hostiles(enemies).filter(e=>!current?.defenderGroup||e.objectiveGroup===current.defenderGroup),target=defenders.length?nearest(aliveSquad(squad)[0]||squad[0],defenders):z;for(const s of aliveSquad(squad))moved=moveActor(s,target,dt)||moved;const fighting=combatStep(dt,current);if(fighting)combat+=dt;for(const e of hostiles(enemies))if(e.path)navigation.followPath(e,78,dt);tactics.fixedUpdate(dt);behaviour.fixedUpdate(dt);adaptive.update(dt);director.tick(simTime);Health.fixedUpdate(dt);const before=current?.id,state=objectives.update(dt,{living:aliveSquad(squad),enemies,zones,scale});tracker.update(simTime,objectives.manager.all());if(moved||fighting||before!==objectives.manager.current()?.id)lastMeaningful=simTime;else idle+=dt;if(simTime-lastMeaningful>45){stalls++;lastMeaningful=simTime}peakEnemies=Math.max(peakEnemies,hostiles(enemies).length);if(state.complete){finished=true;won=true}else if(state.failed){finished=true;failureReason='objective-failed'}else if(!squad.some(s=>s.alive)){finished=true;failureReason='squad-lost'}else if(simTime>=maxSeconds){finished=true;failureReason='timeout'}}
 function run(){while(!finished)step();const rows=objectives.manager.all(),failed=rows.find(o=>o.status==='FAILED');return baseResult({mission,seed,difficultyName,seconds:simTime,won,failureReason,objective:failed?.id||objectives.manager.current()?.id||rows.at(-1)?.id,objectives:tracker.result(),squad,enemies,ammoStart,ammoEnd:squad.reduce((n,s)=>n+(s.ammo||0),0),grenadesStart,grenadesEnd:grenades,directorActions:director.actions,peakEnemies,combatSeconds:combat,idleSeconds:idle,stalls,shotsFired,shotsHit,skillFactor})}return{mission,map,step,run,get finished(){return finished}}}
function createBarcelona({mission,map,seed,difficultyName,maxSeconds}){
 const scale=2,rng=Rng.create(seed),rules=difficulty(difficultyName),skillFactor=.9+rng.random()*.2,navigation=createNavigation(map,scale),objectives=Objectives.create(mission),zones=zonesFor(map,scale),squad=map.spawns.squad.map(([x,y],i)=>({name:['Joan','Isabel','Pere','Carme'][i]||'S'+(i+1),x:x*scale,y:y*scale,hp:8,maxHp:8,alive:true,dir:0,ammo:0,weapon:null,shotCooldown:0})),enemies=map.spawns.enemies.map(([x,y])=>({x:x*scale,y:y*scale,alive:true,hp:3,maxHp:3,objectiveGroup:'patrol',groupId:'patrol',shotCooldown:.2+rng.random()*.6})),civilians=[];let grenades=0;
 const rawDamage=(u,amount)=>{if(!u.alive)return;u.hp-=amount;if(u.hp<=0){u.alive=false;u.state='dead'}};Health.bindRuntime({getSquad:()=>squad,getSelected:()=>aliveSquad(squad).slice(0,1),damage:rawDamage});
 const civilianRuntime=Civilians.create({getCivilians:()=>civilians,getSquad:()=>squad,getEnemies:()=>enemies,zones:[zones.safe],scale,move:(u,dx,dy,r=6)=>{if(!navigation.obstacleAt(u.x+dx,u.y,r))u.x+=dx;if(!navigation.obstacleAt(u.x,u.y+dy,r))u.y+=dy},canOccupy:(x,y)=>!navigation.obstacleAt(x,y,6),path:navigation.assignPath,follow:navigation.followPath});
 const runtime=BarcelonaRuntime.create({map,objectives,getSquad:()=>squad,getEnemies:()=>enemies,navigation,scale,random:rng.random,getResidents:()=>civilians,spawnResidents:()=>map.rescue.positions.forEach(([x,y],i)=>civilianRuntime.add({x:x*scale,y:y*scale,homeX:x*scale,homeY:y*scale,phase:i,speed:35,civilianState:'HIDING'})),reposition(){},spawnAllowed:()=>true,setGrenades:n=>{grenades=n},spawn(group,wave){enemies.push(...group.positions.map((p,i)=>({x:p[0]*scale,y:p[1]*scale,alive:true,hp:3,maxHp:3,groupId:String(wave),combatRole:group.roles?.[i],shotCooldown:.2+rng.random()*.5})))}}),tactics=Tactics.create({getSquad:()=>squad,getEnemies:()=>enemies,obstacleAt:navigation.obstacleAt,canSee:(a,b)=>!navigation.lineBlocked(a.x,a.y,b.x,b.y)}),behaviour=EnemyBehaviour.create({getEnemies:()=>enemies,getSquad:()=>squad,autoCommanders:false}),roads=(map.roads||[]).map(r=>({...r,points:r.points.map(p=>p.map(v=>v*scale))}));let simTime=0;
 const commander=Adaptive.createCommander({getEnemies:()=>enemies,getSquad:()=>squad,getZones:()=>zones,getPhase:()=>{const o=objectives.manager.current();return o?{...o,index:o.phase??0}:null},roads,scale,navigation,blocked:navigation.obstacleAt,queuePath:(e,x,y)=>navigation.assignPath(e,x,y),autoCommanders:false}),adapter={sample:(...a)=>({...commander.sample(...a),...runtime.directorContext()}),valid:(action,...a)=>runtime.canDirect(action)&&commander.valid(action,...a),execute:(action,...a)=>{const ok=commander.execute(action,...a);if(ok)runtime.onDirectorDecision(action);return ok},maintain:(...a)=>commander.maintain(...a),release:(...a)=>commander.release(...a)},adaptive=Adaptive.create({mission:'barcelona',adapter,random:rng.random,debug:true}),director=directorRecorder(adaptive),tracker=objectiveTracker();
 let peakEnemies=0,combat=0,idle=0,stalls=0,lastMeaningful=0,lastDecision=-1,shotsFired=0,shotsHit=0,finished=false,won=false,failureReason=null,escortStarted=false,buildTargetMaterial=0;const ammoStart=18,grenadesStart=2;
 function moveActor(actor,target,dt){if(!target||!actor.alive||actor.downed)return false;if(!actor.path||dist(actor,target)>45&&!actor.navDestination)navigation.assignPath(actor,target.x,target.y);const x=actor.x,y=actor.y;navigation.followPath(actor,115*rules.speed*Health.movementScale(actor)*Tactics.movementScale(actor),dt);return Math.hypot(actor.x-x,actor.y-y)>.01}
 function damageEnemy(e,amount,by){if(!e.alive)return false;e.hp-=amount;e.lastHitBy=by;e.lastHitSide='squad';if(e.hp<=0){e.alive=false;e.hp=0;e.state='dead'}return true}
 function combatStep(dt){let active=false;const live=aliveSquad(squad),foes=hostiles(enemies);for(let i=0;i<squad.length;i++){const s=squad[i];s.shotCooldown=Math.max(0,(s.shotCooldown||0)-dt);if(!s.alive||s.downed||!s.weapon||s.ammo<=0)continue;const target=nearest(s,foes.filter(e=>dist(s,e)<300&&!navigation.lineBlocked(s.x,s.y,e.x,e.y)));if(!target||s.shotCooldown>0)continue;active=true;s.shotCooldown=.34+rng.random()*.2;s.ammo--;shotsFired++;if(rng.random()<Math.max(.12,rules.playerHit*skillFactor/Tactics.spreadScale(s))){shotsHit++;damageEnemy(target,1,i)}else tactics.nearShot('squad',s.x,s.y,target.x,target.y)}const cluster=foes.filter(e=>live.some(s=>dist(s,e)<100));if(grenades>0&&cluster.length>=3&&rng.random()<dt*.45){grenades--;active=true;for(const e of cluster.slice(0,4))damageEnemy(e,2,0)}for(const e of foes){e.shotCooldown=Math.max(0,(e.shotCooldown||0)-dt);const target=nearest(e,live.filter(s=>dist(s,e)<290&&!navigation.lineBlocked(e.x,e.y,s.x,s.y)));if(!target||e.shotCooldown>0)continue;active=true;e.shotCooldown=.6+rng.random()*.5;if(rng.random()<rules.enemyHit)Health.handleDamage(target,rules.enemyDamage,target.x,target.y,e);else tactics.nearShot('enemy',e.x,e.y,target.x,target.y)}return active}
 function targetFor(current,lead){if(!current)return null;const id=current.id;if(id==='opening')return zones.junction;if(id==='patrol')return nearest(lead,hostiles(enemies))||zones.contact;if(id==='acquire-weapons')return zones.contact;if(id==='reach-barricade')return zones.barricade;if(id==='build-barricade'){const hint=runtime.hint(lead);if(hint==='REINFORCE'||hint==='DROP MATERIAL'||hint.startsWith('MATERIALS'))return zones.barricade;const p=map.barricade.materials[buildTargetMaterial%map.barricade.materials.length];return{x:p.x*scale,y:p.y*scale,r:35}}if(id==='hold-barricade'||id==='recovery')return zones.barricade;if(id==='reach-civilians')return zones.residents;if(id==='escort-civilians')return escortStarted?zones.safe:zones.residents;if(id==='second-route'||id==='hold-east')return zones.eastern;if(id==='counterattack')return zones.advance;return current.zone?zones[current.zone]:null}
 function interactFor(current,lead){if(!current||!lead)return false;const id=current.id;if(id==='acquire-weapons'&&runtime.hint(lead))return runtime.interact(lead);if(id==='build-barricade'&&runtime.hint(lead)){const action=runtime.hint(lead),ok=runtime.interact(lead);if(ok&&action==='REINFORCE')buildTargetMaterial++;return ok}if(id==='escort-civilians'&&!escortStarted&&dist(lead,zones.residents)<=zones.residents.r){escortStarted=civilianRuntime.interact(lead)||escortStarted;return escortStarted}return false}
 function step(dt=FIXED_DT){if(finished)return;simTime+=dt;tracker.update(simTime,objectives.manager.all());const current=objectives.manager.current(),lead=aliveSquad(squad)[0];let moved=false,acted=false;const downed=squad.find(s=>s.alive&&s.downed&&!s.stabilised);if(downed&&lead&&lead!==downed){moved=moveActor(lead,downed,dt)||moved;if(dist(lead,downed)<=Health.AID_RANGE){Health.stabilise(downed,lead);acted=true}}const target=lead?targetFor(current,lead):null;for(const s of aliveSquad(squad))moved=moveActor(s,target,dt)||moved;if(lead&&simTime-lastDecision>=.25){lastDecision=simTime;acted=interactFor(current,lead)||acted}const fighting=combatStep(dt);if(fighting)combat+=dt;const enemyGoal=current?.id==='hold-east'?zones.eastern:current?.id==='counterattack'?zones.advance:current?.id==='escort-civilians'?zones.residents:current?.id==='hold-barricade'?zones.barricade:null;for(const e of hostiles(enemies)){if(enemyGoal&&!e.path&&!e.commandOrder)navigation.assignPath(e,enemyGoal.x,enemyGoal.y);if(e.path)navigation.followPath(e,72,dt)}tactics.fixedUpdate(dt);behaviour.fixedUpdate(dt);adaptive.update(dt);director.tick(simTime);Health.fixedUpdate(dt);civilianRuntime.update(dt);runtime.update(dt);const state=objectives.update(dt,{living:aliveSquad(squad),enemies,zones});tracker.update(simTime,objectives.manager.all());if(moved||acted||fighting)lastMeaningful=simTime;else idle+=dt;if(simTime-lastMeaningful>45){stalls++;lastMeaningful=simTime}peakEnemies=Math.max(peakEnemies,hostiles(enemies).length);if(state.complete){finished=true;won=true}else if(state.failed){finished=true;failureReason='objective-failed'}else if(!squad.some(s=>s.alive)){finished=true;failureReason='squad-lost'}else if(simTime>=maxSeconds){finished=true;failureReason='timeout'}}
 function run(){while(!finished)step();const rows=objectives.manager.all(),summary=runtime.summary(),failed=rows.find(o=>o.status==='FAILED'),result=baseResult({mission,seed,difficultyName,seconds:simTime,won,failureReason,objective:failed?.id||objectives.manager.current()?.id,objectives:tracker.result(),squad,enemies,ammoStart,ammoEnd:squad.reduce((n,s)=>n+(s.ammo||0),0),grenadesStart,grenadesEnd:grenades,directorActions:director.actions,peakEnemies,combatSeconds:combat,idleSeconds:idle,stalls,civiliansFound:summary.civiliansFound,civiliansRescued:summary.civiliansRescued,civiliansLost:summary.civiliansLost,shotsFired,shotsHit,skillFactor});runtime.dispose();return result}return{mission,map,step,run,get finished(){return finished}}}
function createCable({mission,map,seed,difficultyName,maxSeconds}){
 const scale=2,rng=Rng.create(seed),rules=difficulty(difficultyName),skillFactor=.9+rng.random()*.2,scaledMap={...map,width:map.width*scale,height:map.height*scale,buildings:(map.buildings||[]).map(b=>({...b,points:b.points.map(p=>p.map(v=>v*scale))}))},navigation=CableVerify.createNavigation(scaledMap),privateMission=Historical.get('cable-street-1936'),controller=Cable.createController({mission:privateMission});controller.attachNavigation(navigation);
 const actors=map.spawns.squad.map(([x,y],i)=>({id:'player-'+i,name:'Volunteer '+(i+1),x:x*scale,y:y*scale,active:true,alive:true,hp:8,maxHp:8})),interactions=CableInteractions.create({controller,runtime:Cable,mission:privateMission,options:{scale,pressureControlled:true,navigation}});interactions.initialize({mapData:map,actors});
 const regroup={x:map.regroupPoint.x*scale,y:map.regroupPoint.y*scale},directorRuntime=CableDirector.create({controller,mission:privateMission,options:{regroupPoint:regroup,regroupRadius:48}}),crowd=CableCrowd.create({controller,mission:privateMission,worldWidth:map.width*scale,worldHeight:map.height*scale,navigation,blocked:navigation.obstacleAt}),adapter=Adaptive.createCableAdapter({controller,director:directorRuntime,interactions,crowd}),adaptive=Adaptive.create({mission:'cable-street',adapter,random:rng.random,debug:true}),director=directorRecorder(adaptive),tracker=objectiveTracker();
 let simTime=0,peakEnemies=0,combat=0,idle=0,stalls=0,lastMeaningful=0,lastDecision=-1,finished=false,won=false,failureReason=null,shotsFired=0,shotsHit=0;const ammoStart=0,grenadesStart=0,snap=()=>directorRuntime.snapshot(),actorList=()=>[...controller.state.actors.values()].filter(a=>a.active!==false);
 function move(actor,p,dt){if(!actor||!p)return false;if(!actor.path&&!actor.navDestination)navigation.assignPath(actor,p.x,p.y);const x=actor.x,y=actor.y;navigation.followPath(actor,230*rules.speed,dt);return Math.hypot(actor.x-x,actor.y-y)>.01}
 function assign(actor,targetType,targetId,action){if(!actor||actor.job)return false;try{return interactions.assignJob(actor.id,{action,targetType,targetId})}catch(_){return false}}
 function operate(){const state=snap(),list=actorList(),lead=list[0];if(!lead)return false;let acted=false;if(state.phaseId==='build-barricade'||state.phaseId==='hold-approach'){const b=controller.state.barricades.get('B');if(b.integrity<60){const material=lead.carrying?controller.state.materials.get(lead.carrying):[...controller.state.materials.values()].find(m=>!m.consumed&&!m.carriedBy&&!m.reservedBy);if(material){if(!lead.carrying&&dist(lead,material)<45)acted=assign(lead,'material',material.id,'carry')||acted;else if(lead.carrying&&dist(lead,b.workPoints[0])<45)acted=assign(lead,'barricade','B','reinforce')||acted}}if(state.phaseId==='hold-approach'&&b.integrity>=30&&dist(lead,b.workPoints[0])<50)acted=assign(lead,'barricade','B','hold')||acted}else if(state.phaseId==='regroup'&&dist(lead,regroup)<60)acted=true;else if(state.phaseId==='they-shall-not-pass'){const defences=[...controller.state.barricades.values()],weak=defences.slice().sort((a,b)=>a.integrity-b.integrity)[0];if(weak&&weak.integrity<55){const repairer=weak.id==='S'?list[2]||lead:lead,material=repairer.carrying?controller.state.materials.get(repairer.carrying):[...controller.state.materials.values()].find(m=>!m.consumed&&!m.carriedBy&&!m.reservedBy);if(material){if(!repairer.carrying&&dist(repairer,material)<45)acted=assign(repairer,'material',material.id,'carry')||acted;else if(repairer.carrying&&dist(repairer,weak.workPoints[0])<45)acted=assign(repairer,'barricade',weak.id,'reinforce')||acted}}}return acted}
 function targetFor(actor){const state=snap();if(state.phaseId==='regroup')return regroup;if(state.phaseId==='they-shall-not-pass'){const defs=[...controller.state.barricades.values()],index=Number(actor.id.split('-').at(-1))||0;return defs[Math.floor(index/2)%defs.length]?.workPoints[index%2]||regroup}const b=controller.state.barricades.get('B');if((state.phaseId==='build-barricade'||state.phaseId==='hold-approach')&&b){if(actor.carrying)return b.workPoints[0];const material=[...controller.state.materials.values()].find(m=>!m.consumed&&!m.carriedBy&&!m.reservedBy);return material||b.workPoints[0]}return b?.workPoints?.[0]||regroup}
 function step(dt=FIXED_DT){if(finished)return;simTime+=dt;const state=snap(),pseudoRows=(privateMission.phases||[]).map((p,i)=>({id:p.id||'phase-'+i,status:i<state.phaseIndex?'COMPLETED':i===state.phaseIndex?'ACTIVE':'PENDING'}));tracker.update(simTime,pseudoRows);let moved=false,acted=false,fighting=false;for(const a of actorList())moved=move(a,targetFor(a),dt)||moved;if(simTime-lastDecision>=.2){lastDecision=simTime;acted=operate()||acted}if(['hold-approach','they-shall-not-pass'].includes(state.phaseId)){const intensity=Math.max(.25,skillFactor*rules.playerHit);for(const a of actorList())if(rng.random()<dt*(2.2*intensity)){const hit=interactions.streetAttack(a.id,{kind:'throw'});fighting=hit||fighting;shotsFired++;if(hit)shotsHit++}}interactions.fixedUpdate(dt);directorRuntime.fixedUpdate(dt);crowd.fixedUpdate(dt);adaptive.update(dt);director.tick(simTime);if(fighting)combat+=dt;const next=snap(),formations=[...controller.state.formations.values()].filter(f=>!['withdraw','regroup'].includes(f.state));peakEnemies=Math.max(peakEnemies,formations.length);if(moved||acted||fighting||next.phaseIndex!==state.phaseIndex)lastMeaningful=simTime;else idle+=dt;if(simTime-lastMeaningful>45){stalls++;lastMeaningful=simTime}if(next.completed){finished=true;won=true}else if(next.failed){finished=true;failureReason=next.failureReason||next.status||'objective-failed'}else if(simTime>=maxSeconds){finished=true;failureReason='timeout'}}
 function run(){while(!finished)step();const state=snap(),squad=actorList().map(a=>({...a,alive:a.active!==false})),result=baseResult({mission,seed,difficultyName,seconds:simTime,won,failureReason,objective:state.phaseId,objectives:tracker.result(),squad,enemies:[],ammoStart,ammoEnd:0,grenadesStart,grenadesEnd:0,directorActions:director.actions,peakEnemies,combatSeconds:combat,idleSeconds:idle,stalls,shotsFired,shotsHit,skillFactor});controller.dispose();return result}return{mission,map,step,run,get finished(){return finished}}}
function init(options={}){const ref=options.mission||'bad-belzig',seed=options.seed??1,difficultyName=options.difficulty||'standard',maxSeconds=Math.max(1,Number(options.maxSeconds)||DEFAULT_MAX_SECONDS);if(!DIFFICULTY[difficultyName])throw new Error('Unsupported difficulty: '+difficultyName);const{definition,mission}=missionFor(ref),map=mapFor(definition),args={mission,map,seed,difficultyName,maxSeconds};if(definition.map.key==='barcelona')return createBarcelona(args);if(definition.map.key==='cable-street')return createCable(args);return createStandard(args)}
function simulateMission(options={}){return init(options).run()}
function inspectMission(ref){const{definition,mission}=missionFor(ref),map=mapFor(definition);return{id:mission.id,key:definition.key,map:definition.map.key,runtime:definition.runtime.type,phases:(mission.phases||[]).length,mapReady:!!map}}
function supportedMissions(){return Registry.all().map(d=>d.id)}
module.exports={FIXED_DT,DEFAULT_MAX_SECONDS,DIFFICULTY,init,simulateMission,inspectMission,supportedMissions,percentile};
